version: '3.8'
services:
  service1:
    build: ./api_colour
    image: zake99/service1:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    build: ./api-food
    image: zake99/service2:latest
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    build: ./api-drink
    image: zake99/service3:latest
    ports:
    - target: 5050
      published: 5050
      protocol: tcp
  service4:
    build: ./api-post
    image: zake99/service4:latest
    ports:
    - target: 5005
      published: 5005
      protocol: tcp