---
- hosts: nginx
  become: true
  roles:  
  - role: nginx
- hosts: workers
  become: true
  roles:
    - docker
    - worker
- hosts: workers
  become: true
  roles:
    - docker
    - manager


  - hosts: worker 
  - name: Git clone
    ansible.builtin.git:
      repo: 'https://github.com/Zake-Ahmed/team-Earth-GP.git'
      dest: ./flask-app
      single_branch: yes
      version: ansible
